# Generated by Django 2.2.1 on 2019-05-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoRider',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('starting_point', models.CharField(max_length=45)),
                ('destination', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('room', models.IntegerField()),
                ('n_stops', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rites.Rider')),
            ],
        ),
        migrations.CreateModel(
            name='RideGuest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rites.Ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rites.NoRider')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rites.Rider'),
        ),
        migrations.CreateModel(
            name='IntermediateStop',
            fields=[
                ('id_stop', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=45)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rites.Ride')),
            ],
        ),
    ]
